[workspace]

members = [
    "gcd",
    "heap",
    "bubble_sort",
    "merge_sort",
    "quick_sort",
    "rand",
    "fibonacci",
    "list",
    "dlist",
    "tree",
    "balanced_tree",
    "skip_list",
    "huffman",
    "graph",
    "shortest_path",
]
